### ISSUE TITLE
Language ar, es, et, nl need an update to 2.0.2

### ISSUE THREAD

**Issue by Crizz0** [Crizz0/phpbb3-about-us#14]
@alhitary

@David-NF 

@phpBBeesti 

Please add two no variables: 
'ABOUTUS_ENABLE'
'ABOUTUS_ENABLE_EXPLAIN'

**Comment by David-NF** [comment]
Working on it as we speak... PR in a few minutes.

**Comment by alhitary** [comment]
Ok dear

**Comment by Crizz0** [comment]
AR check with #16 
NL check with #15 

Thank you, for your fast response. 

Lets wait for ES and ET.

**Comment by Crizz0** [comment]
ES via #18 

Thank you!

**Comment by Crizz0** [comment]
ET done! Thx.

Close via #19
