### ISSUE TITLE
Ordered list doesn't work

### ISSUE THREAD

**Issue by ivanovd** [Crizz0/phpbb3-about-us#22]
When I tried to insert an ordered list, e.g. 
[list=1]
[_]blah
[_]blah2
[/list]

It shows it as unordered when I open the About us page

**Comment by Crizz0** [comment]
Hi,

thanks for your report.

You try this: https://github.com/Crizz0/phpbb3-simple-imprint/commit/51b0cf2a90d7d1ae1e4e073728f41f05d72e8dff It should fix the problem. :)

**Comment by ivanovd** [comment]
Yup, that seemed to have fixed the issue. Thanks for the prompt action.

Cheers

**Comment by Crizz0** [comment]
Will be in 2.0.4. Until that release, please edit the code on your own. :)

**Comment by Crizz0** [comment]
Fixed with: https://github.com/Crizz0/phpbb3-simple-imprint/commit/51b0cf2a90d7d1ae1e4e073728f41f05d72e8dff
