### ISSUE TITLE
Are all language files up to date?

### ISSUE THREAD

**Issue by Crizz0** [Crizz0/phpbb3-about-us#29]
- [x] Czech @R3gi  
- [x] French @Galixte 
- [x] Turkish @denizlikoyu 
- [x] German (me & myself) Myself
- [x] English (me & myself)
- [x] Arabic @alhitary 
- [x] Spanish @phpbb-es 
- [x] Estonian @phpBBeesti 
- [x] Dutch @David-NF 

Think of #28 ! There won't be any additional functions, so the english files are up to date. 

There is a deadline, who will not give me his okay, i will remove the language pack and bring it in 2.0.5 or higher. 

Thank you :)

**Comment by alhitary** [comment]
Mine is up 2 date.

**Comment by Crizz0** [comment]
:+1: :)

**Comment by David-NF** [comment]
Not at this moment, but I'm going to work on it right now!

**Comment by David-NF** [comment]
Just added a pull request, out translation is up-to-date after https://github.com/Crizz0/phpbb3-about-us/compare/version2_0...David-NF:patch-3 is merged.

**Comment by Crizz0** [comment]
Merged.

**Comment by R3gi** [comment]
Hi, yes, it seems Czech is up to date too :)

**Comment by Crizz0** [comment]
Ah, thx. I should have known, that 23.10. is no challenge for you. :D

**Comment by Galixte** [comment]
Hi @Crizz0, now french is OK, here: https://github.com/Crizz0/phpbb3-about-us/pull/32. ;)

**Comment by DrByRz** [comment]
Turkish is OK

**Comment by phpbb-es** [comment]
Spanish updated, and changed English file Crizz0, verify all language files about this Small problem:
https://github.com/phpbb-es/phpbb3-simple-imprint/commit/ba91dcafce17f46fc3961eb8fceead86309e719f

Best regards.

**Comment by ghost** [comment]
Estonian is OK.

**Comment by Crizz0** [comment]
K. Thank you.
