### ISSUE TITLE
Language file need update for META-INdex

### ISSUE THREAD

**Issue by Crizz0** [Crizz0/phpbb3-about-us#51]
Hi,

please update your language files for the Release 2.1.3:
- [x] @phpbb-es  - Spanish
- [ ] @Galixte - French
- [ ] @eunaumtenhoid - pt_br 
- [ ] @alhitary 
- [x] Dutch
- [x] @R3gi #52 - Czech
- [x] @DrByRz  - Turkish 
- [ ] @ForumsFaciles 

Changes:
```
diff --git a/language/en/common.php b/language/en/common.php
index bc794b3..6342e2c 100644
--- a/language/en/common.php
+++ b/language/en/common.php
@@ -57,6 +57,9 @@ $lang = array_merge($lang, array(
 	'ACP_PRIVACY_ENABLE' 				=> 'Display privacy policy',
 	'ACP_PRIVACY_ENABLE_EXPLAIN'		=> 'Displays a link to the privacy policy on the “About us”-page.',
 
+	'ACP_META_NOINDEX_ENABLE'			=> 'Meta noindex',
+	'ACP_META_NOINDEX_ENABLE_EXPLAIN'	=> 'Tells search engine robots, that they must not index the “About us”-page. This option will not prevent robots from indexing the “About us”-page anyway!',
+
 	'DESCRIPTION_PRIVACY'			=> 'You can see the privacy policy here:',
 	'DESCRIPTION_TERMS_OF_USE'		=> 'You can see the terms of use here:',
 	'DESCRIPTION_PRIVACY_TERMS_OF_USE'=> 'You can see the terms of use and privacy policy here:',

```

Send your PullRequest until 24.01.2020.

Not updated languages will be removed before release.

**Comment by R3gi** [comment]
Hi, thanks for notification, see linked PR.

Copyright year should be probably updated too.

**Comment by Crizz0** [comment]
Thank you, 6 to go :)

**Comment by DrByRz** [comment]
this is Turkish (tr) translation.
i added translation info and added the 2 line. and a minor correction.

Christian Schnegelberger <notifications@github.com>, 21 Oca 2020 Sal, 01:03
tarihinde şunu yazdı:

**Comment by Crizz0** [comment]
@Galixte @eunaumtenhoid @alhitary any timeplan?

**Comment by Crizz0** [comment]
Okay, fr, ar, pt_br and et got removed.

**Comment by Galixte** [comment]
@Crizz0 I’ll do that tomorrow, thanks for pm me.
