### ISSUE TITLE
Updated docker now can't access acp

### ISSUE THREAD

**Issue by techguruz** [Crizz0/phpbb3-about-us#55]
Looks like I should have disabled this before hand unfortunately I have my dockers set to auto update. The creator of the docker had forgot to add the persistent storage and updated the docker to add it in, which in turn messed some stuff up and I am now hitting this error when trying to access the acp.

PHP Fatal error: Uncaught Symfony\\Component\\Routing\\Exception\\RouteNotFoundException: Unable to generate a URL for the named route "crizzo_aboutus" as such route does not exist. in /opt/bitnami/phpbb/cache/production/url_generator.php:44\nStack trace:\n#0 /opt/bitnami/phpbb/phpbb/routing/router.php(168): phpbb_url_generator->generate('crizzo_aboutus', Array, 1)\n#1 /opt/bitnami/phpbb/phpbb/routing/helper.php(148): phpbb\\routing\\router->generate('crizzo_aboutus', Array, 1)\n#2 /opt/bitnami/phpbb/phpbb/controller/helper.php(114): phpbb\\routing\\helper->route('crizzo_aboutus', Array, true, false, 1)\n#3 /bitnami/phpbb/ext/crizzo/aboutus/event/main_listener.php(76): phpbb\\controller\\helper->route('crizzo_aboutus')\n#4 /opt/bitnami/phpbb/vendor/symfony/event-dispatcher/EventDispatcher.php(214): crizzo\\aboutus\\event\\main_listener->add_page_header_link(Object(phpbb\\event\\data), 'core.page_heade...', Object(phpbb\\event\\dispatcher))\n#5 /opt/bitnami/phpbb/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatch in /opt/bitnami/phpbb/cache/production/url_generator.php on line 44, referer: https://r3v.one/index.php?sid=39cdb308d784374dcaaf09e8b8561ab3

any help would be much appreciate really just need a way to fully disable it so I can access the acp then I can re add it in.

**Comment by Crizz0** [comment]
Hi,

check your server and re-upload my extension in the version you had to the place where it was. Purge the cache-directory (delete all contents without index.htm and .htaccess).

Then it should work.

Don't delete extensions without uninstalling them correctly.

Regards

**Comment by Crizz0** [comment]
And this is not an issue.

Support is available at www.phpbb.de, www.phpbb.com and www.crizzo.de

Regards
